# syntax=docker/dockerfile:1
FROM docker.io/ubuntu:24.04
ENV WORKSPACE="/workspace"

RUN set -eux \
    && apt-get update \
    && apt-get full-upgrade -y --no-install-recommends \
    && apt-get install -y --no-install-recommends curl ca-certificates zstd \
    && curl -fsSL https://tailscale.com/install.sh | sh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR ${WORKSPACE}

COPY . /container/

RUN set -eux \
    && chmod u+x /container/entrypoint.sh

# NVIDIAランタイムの設定
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV NVIDIA_DISABLE_REQUIRE=1

EXPOSE 11434
CMD ["bash", "/container/entrypoint.sh"]
